### ISSUE TITLE
ServerRequest.path no longer exists

### ISSUE THREAD

**Issue by krry** [one-aalam/svelte-starter-kit#25] opened 2022-01-16 02:00 UTC
Encountered a ts error in `src/hooks/index.ts:13`

I suspect this can be resolved by changing it to:
```ts
   if (request.method === 'POST' && request.url.pathname === API_AUTH) {
```

Testing soon…

**Comment by one-aalam** [comment] 2022-01-21 10:26
Thanks for opening the issue @krry and the solution. As the per the latest SvelteKit updates there's good amount of updates this repo might receive. I hope and look forward  to resolve all the open issues as per the latest SvelteKit update in next sitting, most definitely in a week's time.

**Comment by ersanuensal** [comment] 2022-01-21 13:08
In the new svelte version "request" got replaced by "event". I havent figured it out how to fix the hook.

event.url.pathname works i think but request.method has an issue.

**Comment by akiarostami** [comment] 2022-01-27 22:00
@one-aalam & @ersanuensal, have you been able to find a way to make the new SvelteKit work with Supabase's auth?

**Comment by one-aalam** [comment] 2022-01-29 17:09
Hey @akiarostami @ersanuensal @krry Thank you for patience. The issue is fixed now. Please checkout the latest from `main`

Happy Coding,
Aftab

**Comment by akiarostami** [comment] 2022-01-31 22:35
Hi Aftab,

Thank you for the update, and for the great work! I have been playing around with this as well, and I think I might have a simpler solution, which also takes care of renewing tokens on the server side (which I believe your code doesn't do). Let me know if you're interested and I'll share the code.

**Closed** 2022-02-04 15:13 UTC
